#!/bin/bash

cd ~/
ln -s dotfiles/.gitignore .gitignore
ln -s dotfiles/.gitconfig .gitconfig
ln -s dotfiles/.vim .vim
ln -s dotfiles/.vimrc .vimrc
ln -s dotfiles/.zshrc .zshrc
ln -s dotfiles/.tmux.conf .tmux.conf


